---
kind: ResourceQuota
apiVersion: v1
metadata:
  name: goappdemo1-quota
  namespace: goappdemo1
  labels:
    kubernetes.io/metadata.name: goappdemo1
    backstage.io/kubernetes-id: goappdemo1
    istio-injection: enabled
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "2"
    limits.memory: 2Gi