---
kind: ResourceQuota
apiVersion: v1
metadata:
  name: testgoapp2-quota
  namespace: testgoapp2
  labels:
    kubernetes.io/metadata.name: testgoapp2
    backstage.io/kubernetes-id: testgoapp2
    istio-injection: enabled
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "2"
    limits.memory: 2Gi