apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: testgoapp2-hpa
  labels:
    app: testgoapp2
    version: 0.0.1
    backstage.io/kubernetes-id: testgoapp2
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: testgoapp2
 minReplicas: 1
 maxReplicas: 4
 targetCPUUtilizationPercentage: 75