---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: testgoapp3
resources:
  - ns.yaml
  - testgoapp3-quota.yaml
  - testgoapp3-deploy.yaml
  - testgoapp3-svc.yaml
  - testgoapp3-vs.yaml
  - testgoapp3-hpa.yaml