---
kind: ResourceQuota
apiVersion: v1
metadata:
  name: testgoapp3-quota
  namespace: testgoapp3
  labels:
    kubernetes.io/metadata.name: testgoapp3
    backstage.io/kubernetes-id: testgoapp3
    istio-injection: enabled
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "2"
    limits.memory: 2Gi