---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gotestapp5
resources:
  - ns.yaml
  - gotestapp5-quota.yaml
  - gotestapp5-deploy.yaml
  - gotestapp5-svc.yaml
  - gotestapp5-vs.yaml
  - gotestapp5-hpa.yaml