---
kind: ResourceQuota
apiVersion: v1
metadata:
  name: goapprealtest-quota
  namespace: goapprealtest
  labels:
    kubernetes.io/metadata.name: goapprealtest
    backstage.io/kubernetes-id: goapprealtest
    istio-injection: enabled
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "2"
    limits.memory: 2Gi