apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: gotestapp4-hpa
  labels:
    app: gotestapp4
    version: 0.0.1
    backstage.io/kubernetes-id: gotestapp4
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: gotestapp4
 minReplicas: 1
 maxReplicas: 4
 targetCPUUtilizationPercentage: 75