---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gotestapp4
resources:
  - ns.yaml
  - gotestapp4-quota.yaml
  - gotestapp4-deploy.yaml
  - gotestapp4-svc.yaml
  - gotestapp4-vs.yaml
  - gotestapp4-hpa.yaml