---
kind: ResourceQuota
apiVersion: v1
metadata:
  name: gotestapp6-quota
  namespace: gotestapp6
  labels:
    kubernetes.io/metadata.name: gotestapp6
    backstage.io/kubernetes-id: gotestapp6
    istio-injection: enabled
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "2"
    limits.memory: 2Gi