apiVersion: apps/v1
kind: Deployment
metadata:
  name: samplegoapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: samplegoapp
  template:
    metadata:
      labels:
        app: samplegoapp
    spec:
      containers:
      - name: webserver-simple
        image: docker.io/jaydeepfis/samplegoapp:latest
        ports:
        - containerPort: 8080
